/**
 * Garage Invoices — withdrawal requests generated by approved garages.
 */
import { InvoiceTable } from '@/components/admin/invoice-table'
import { PageHeader } from '@/components/shared/page-header'
import { SectionShell } from '@/components/shared/section-shell'
import { getGarageInvoices } from '@/lib/admin/queries-invoices'

export const metadata = { title: 'Admin · Garage Invoices' }

export default async function GarageInvoicesPage() {
  const rows = await getGarageInvoices()

  return (
    <div className="space-y-6">
      <PageHeader kicker="Money" title="Garage Invoices" />
      <SectionShell title="Garage Withdrawals">
        <InvoiceTable rows={rows} />
      </SectionShell>
    </div>
  )
}
